name: 'C++ CI'

on:
  push:
    branches:
      - master
      - feature/github_actions

jobs:
  build_mac_os:
    runs-on: macos-latest
    name: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          
      - run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - run: brew install cmake
      # - run: brew install boost
      - run: cmake . -DPATCH_VERSION=${{ github.run_number }}
      - run: cmake --build .
      - run: cmake --build . --target package
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}_macos
          release_name: Release macOS ${{ github.run_number }}
          draft: false
          prerelease: false
      - name: Upload Release Asset Mac OS
        id: upload-release-asset-mac-os
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./sr_9--Darwin.7z
          asset_name: sr_9--Darwin.7z
          asset_content_type: application/x-7z-compressed
